---
title: "BR regions"    |
author: "@BragatteMAS" |
format: html           |
editor: source         |
---

# Brazil Regions

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  error = FALSE,
  warning = FALSE,
  message = FALSE,
  #cache = TRUE,
  fig.align = "center",
  results = 'asis'
)
```

### libs

```{r}
## delete memory data
rm(list = ls())
```

```{r}
library(pacman)
pacman::p_load(geobr, sf, tidytable, ggplot2, janitor, dplyr, tidyverse, gt)
```

```{r}
#| collapse = FALSE
## add libraries of interest
packs <-
  c(
    "geobr",      ## maps & shape files
    "sf",         ## plot maps
    "tidytable",  ## manipular dados
    "ggplot2",    ## gráficos
    "dplyr",      ## merge
    "janitor"     ## clean data
    )
## install packages if not installed and load libs
if (!require(packs))
  lapply(packs, install.packages, character.only = FALSE)
lapply(packs, require, character.only = TRUE
)
```

### data

```{r}
br.states <- geobr::read_state(code_state ="all",year=2020 )
br.region <- geobr::read_region(2020)
```

#### Create DF of tests

```{r}
br22_tests <- as_tidytable(read.csv("~/Documentos/GitHub/R/Reserarch/tests_2022.csv"))
```

#### Add number of test in 2022 Br

```{r}
data_map <- br22_tests %>% 
  inner_join(br.states, by = "abbrev_state") %>% 
  select(-state, -region) %>% 
  clean_names()
```

#### Manipulate dataset for translation region names

```{r}
# Define a lookup table that maps Portuguese names to English equivalents
translation_table <-
  data.frame(
    from = c("Norte", "Nordeste", "Centro Oeste", "Sudeste", "Sul"),
    to = c("North", "Northeast", "Midwest", "Southeast", "South")
  )

# Replace the region names with their English equivalents
br.region$name_region <-
  translation_table$to[match(br.region$name_region, translation_table$from)]

br.states$name_region <-
  translation_table$to[match(br.states$name_region, translation_table$from)]
```

### plot only states

```{r}
bra <-
  ggplot(br.states) +
  geom_sf(aes(fill = name_region)) +
  geom_sf_label(aes(label = abbrev_state),
                label.padding = unit(0.5, "mm"),
                size = 2) +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(fill = "Region",
       title = "Brazilian regions and states")
bra
```

#### Plot states and tests

```{r}
# Define colors range
pal <- colorRampPalette(c("white", "red"))

# Create color gradient
data_map$grad <- cut(data_map$n_tests, breaks = 10)
data_map$fill <- pal(length(levels(data_map$grad)))[as.integer(data_map$grad)]
```

```{r}
# Create heatmap
heatmap <- ggplot() +
  geom_sf(data = data_map, aes(fill = fill), color = "gray70") +
  geom_sf_label(
    data = data_map,
    aes(label = paste(abbrev_state, n_tests)),
    label.padding = unit(0.5, "mm"),
    size = 2
  ) +
  scale_fill_identity() +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(fill = "Número de testes em 2022 disponibilizados por laboratórios parceiros",
       title = "Estados brasileiros por número de testes") +
  theme_void() +
  theme(panel.background = element_rect(fill = "white", color = NA))

# View map
heatmap
```

```{r}
# group data by region and sum number of tests
data_bar <- data_map %>%
  group_by(name_region) %>%
  summarise(num_tests = sum(n_tests))
```

```{r}
# horizontal bar plot with number of tests by region
ggplot(data_bar, aes(x = reorder(name_region, num_tests), y = num_tests, fill = factor(name_region))) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  xlab("Número de Testes") +
  ylab("Região") +
  labs(title = "Número de testes por região") +
  theme_light() +
  theme(axis.line.y = element_blank(),
        axis.text.y = element_text(size = 10, hjust = 1),
        axis.ticks.y = element_blank(),
        plot.title = element_text(hjust = 0.5),
        panel.grid.major.x = element_line(color = "gray90"),
        panel.grid.minor.x = element_line(color = "gray90"),
        panel.grid.major.y = element_blank()) +
#  geom_text(aes(x = num_testes, y = reorder(regiao, num_testes), label = num_testes),
#            hjust = -0.1, size = 3) +
  scale_y_continuous(labels = scales::comma)
```

```{r}
#tibble::as.tibble(br.states)
tibble::as.tibble(data_map)
```

```{r}
glimpse(data_map)
```

#### Df for new table

```{r}
br_supp_t <- br.states |> 
    select(-c(code_state, abbrev_state, code_region, 'geom')) |> 
    pivot_wider(
    names_from = 'name_region',
    values_from = 'name_state',
    values_fn = list('name_state' = unique)
  )
```

### Creating a new table for supplementary material

```{r}
br_supp_a <- br.states |> 
  pivot_wider(names_from = 'name_region', values_from = 'name_state', 
              values_fn = list(name_state = unique)) |> 
  select(-c(code_state, abbrev_state, code_region, geom))
```

### Gt table

```{r}
br.states %>%
  select(name_state, name_region) %>%
  pivot_longer(cols = -name_region, names_to = "state_type") %>%
  gt()
```
