---
title: "PandasVSDataTable"
author: "Bragatte"
date: "01/03/2021"
output: html_document
Git: 
Info: by @Bragatte 202103011108
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Comparison between Pandas (Py) and Data.Table (R) [Ref](https://towardsdatascience.com/pandas-may-not-be-the-king-of-the-jungle-after-all-f09d061cf121).

1.  Read Dataset e.g.
2.  Libraries R and Py
3.  

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

## DataSets

```{r melb}
melb = pd.read_csv("/content/melb_data.csv", 
usecols = ['Price','Landsize','Distance','Type', 'Regionname'])
```

## Packs

```{r}
#R packages
packs = c("reticulate", "data.table")
lapply(packs, install.packages, character.only = TRUE)
lapply(packs, require, character.only = TRUE)

#importing required Python libraries/modules
pd <- import('pandas')
np <- import('numpy')

```

## Data.table vs Pandas

```{r}

```
