---
title: "Exemplo_denv_extracao"
author: "@BragatteMAS"
format: html
editor: visual
R: 4.3.0
---

## Exemplo para extrair dados de Dengue

```{r}
## Instale e carregue as bibliotecas necessárias
pacman::p_load(tidyverse, tm, slam, stringr, lubridate)

## Pacote para manipulação de dados e visualização
## Pacote para mineração de texto
## Pacote para manipulação eficiente de matrizes esparsas
## Pacote para manipulação de strings
## Pacote para manipular datas
```

```{r}
## Criando um Conjunto de Dados de Exemplo
Data_MV_teorico <- data.frame(
  id = 1:10,
  data = as.Date(
    c(
      '2023-01-01',
      '2023-01-02',
      '2023-01-02',
      '2023-01-03',
      '2023-01-04',
      '2023-01-04',
      '2023-01-05',
      '2023-01-06',
      '2023-01-07',
      '2023-01-07'
    )
  ),
  descricao = c(
    "Paciente com dengue confirmada",
    "Suspeita de dengue",
    "Paciente com sintomas de dengue",
    "Paciente com COVID-19",
    "Paciente com gripe comum",
    "Paciente com dengue confirmada",
    "Suspeita de dengue",
    "Paciente com sintomas de dengue",
    "Paciente com COVID-19",
    "Paciente com gripe comum"
  ),
  stringsAsFactors = FALSE
)
```

```{r}
## Função para extrair linhas que contêm uma palavra específica
extrair_linhas <- function(tabela, coluna, palavras) {
  tabela %>%
    filter(str_detect(!!sym(coluna), regex(palavras, ignore_case = TRUE)))
}

## Extrair linhas que contêm a palavra 'dengue'
dengue_separado <-
  extract_rows(Dado_MV_teorico, "descricao", "dengue")

## Converter o texto em um corpus - termo da biblioteca
corpus <- Corpus(VectorSource(dengue_separado$descricao))
```

```{r}
## Criar uma matriz de documentos por termos
dtm <-
  DocumentTermMatrix(corpus, control = list(wordLengths = c(1, Inf)))

## Converter a dtm em uma matriz
dtmMatrix <- as.matrix(dtm)

## Visualizar a matriz
print(dtmMatrix)

```
