---
title: "Classe_de_Projeto"
author: "BragatteMAS"
format: html
editor: visual
---

## Classe de investimento para Projetos

Modelo de distribuição de investimentos em projetos, dentro de grupos de Inovação ou Estruturante, de modo Anual ou Plurianual.

## Libs

```{r}
## Instale e carregue o pacote gt se ainda não o fez
if (!require(pacman)) install.packages("pacman")
pacman::p_load(gt)
```

## Dados

```{r}
## Criar um data frame de exemplo
df <- data.frame(
  Classe = c("A1", "A2", "B1", "B2"),
  Tipo = c("Estruturante", "Estruturante", "Exploratório", "Exploratório"),
  Investimento = c("Plurianual (R$)", "Anual (R$)", "Plurianual (R$)", "Anual (R$)"),
  Valor = c("500.000 - 1.000.000", "250.000 - 500.000", "250.000 - 500.000", "100.000 - 250.000"),
  Descrição = c("Estruturantes de longo e médio prazo com duração entre 24 a 36 meses", 
                "Estruturantes com foco em planejamento para 12 meses",
                "Caráter inovador, atuando como prova de conceito e duração de até 24 meses",
                "Inovadores de curto prazo (financiamento pontual), atuando como prova de conceito para 12 meses")
)


```

## Tabelas

```{r}
## Criar a tabela gt com a nova estrutura
gt_tbl <- gt(df) %>%
  tab_header(
    title = "Classes de Investimentos em Projetos",
    subtitle = "Atualizado em: 01/11/2023"
  ) %>%
  cols_label(
    Investimento = "Tipo de Investimento"
  ) %>%
  tab_spanner(
    label = "Detalhes do Investimento",
    columns = c("Investimento", "Valor")
  ) %>%
  tab_source_note(source_note = "Fonte: Instituto Todos pela Saúde")

# Exibir tabela
gt_tbl

```
