---
title: "Report Resp"
author: "Bragatte"
format: html
editor: visual
data: 2023-10-30
---

## Report Resp

Última análise de dados de patógenos respiratórios.\
Foco reformat DASA

```{r}

```

```{r}
#########################################
## chama bibliotecas
pacman::p_load(tidyverse, vroom)

## definindo caminho
# setwd("~/Documents/20231025_relatorio27_resp/")
# setwd("~/Downloads/")

## 26_resp
combined <-
  # vroom("results/combined.tsv")
  vroom("combined_dasa_test_final.tsv")

## Quantidade de resultados positivos e negativos por lab:
# test_result by labs
table(combined$SC2_test_result, combined$lab_id)

## Quantidade de tipos de testes por laboratório:
# test_kit by labs
table(combined$test_kit, combined$lab_id)

## Quantidade de testes Positivos e Negativos por estado: 
# Test by state
table(combined$state, combined$SC2_test_result)

## Número de testes por laboratório na última semana:
# test_lab by last week
last_week <- combined[combined$epiweek == "2023-10-21", ] # EDITAR AQUI
table(last_week$lab_id, last_week$epiweek)

## Quantidade de testes Positivos e Negativos por laboratório na última semana
table(last_week$lab_id, last_week$SC2_test_result)

## Quantidade de testes por estado na última semana
# state by last week
table(last_week$state, last_week$epiweek)
```
