---
title: "VacinaBr"
author: "Bragatte"
date: "27/06/2021"
output: html_document

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Acompanhamento da Vacinação no Brasil

### Data cleaning
#### DataSUS
```{r}
#install.packages('vacinaBrasil')

library(ggplot2)
library(vacinaBrasil)
fonte <- stringr::str_glue("Fonte:\n",
                           "População: PNAD Contínua\n",
                           "Vacinação: Open DataSus")
dose <- datasus_idade_sexo_dose %>%
    dplyr::select(sexo, idade, tipo = dose, n) %>%
    dplyr::filter(tipo %in% c("1ª Dose", "2ª Dose"))
pop <- pop_idade_sexo %>%
    dplyr::transmute(sexo,
                     idade = as.numeric(idade),
                     tipo = "População",
                     n = pop) %>%
    dplyr::filter(idade <= 100, idade >= 18)
dados <- dplyr::bind_rows(pop, dose)
dados %>%
    dplyr::mutate(n = n * ((sexo == "Homem") * 2 - 1)) %>%
    dplyr::mutate(tipo = forcats::lvls_reorder(tipo, c(2, 1, 3))) %>%
    ggplot(aes(
        x = n,
        y = factor(idade),
        fill = sexo,
        alpha = tipo
    )) +
    geom_col(width = 1, position = "identity") +
    annotate(
        geom = "text",
        x = 0,
        y = seq(3, 73, 10),
        label = seq(20, 90, 10)
    ) +
    scale_x_continuous(breaks = seq(-1500, 1500, 500) * 1000,
                       labels = paste0(abs(seq(-1500, 1500, 500)), "K")) +
    scale_y_discrete(breaks = seq(0, 100, 10)) +
    scale_fill_viridis_d(begin = .3,
                         end = .8,
                         option = "C") +
    scale_alpha_manual(values = c(1, .6, .3)) +
    theme_minimal() +
    labs(
        x = "População",
        y = "Idade",
        fill = "",
        alpha = "",
        title = "Vacinação no Brasil",
        caption = fonte
    ) +
    guides(fill = guide_legend(reverse = TRUE)) +
    theme(
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "top",
        plot.title = element_text(hjust = .5)
    )
```


```{r}
# code to prepare `datasus` dataset goes here

# download ----------------------------------------------------------------

## Acessa link do arquivo
ckanr::ckanr_setup("https://opendatasus.saude.gov.br")

link <- ckanr::package_search("vacina") %>%
    purrr::pluck("results", 1, "resources") %>%
    purrr::keep( ~ length(.x$mimetype) > 0 &&
                     .x$mimetype == "text/csv") %>%
    purrr::pluck(1, "description") %>%
    stringr::str_extract("(?<=Dados Completos\\]\\()[^\\)]+") %>%
    stringr::str_squish()

## Acessa link do arquivo
f <- fs::file_temp("vacinas", ext = ".csv")
httr::GET(link, httr::write_disk(f, TRUE), httr::progress())

# import ------------------------------------------------------------------

n_rows <- length(vroom::vroom_lines(f)) - 1L
chunk_size <- 1e7
n_chunks <- ceiling(n_rows / chunk_size)
skips <- chunk_size * seq(0, n_chunks - 1) + 1

colunas <- c("paciente_idade",
             "paciente_enumSexoBiologico",
             "vacina_descricao_dose")

estrutura_dados <- vroom::vroom(f, n_max = 100, col_types = "")
nm <- names(estrutura_dados)
colunas_spec <- rep("_", length(nm))
colunas_spec[nm %in% colunas] <- "c"
colunas_spec <- paste(colunas_spec, collapse = "")

sumarizar <- function(skip, f, chunk_size, colunas, colunas_spec) {
    message(skip)
    dados <- vroom::vroom(
        file = f,
        skip = skip,
        n_max = chunk_size,
        col_types = colunas_spec,
        col_names = FALSE
    )
    dados %>%
        purrr::set_names(colunas) %>%
        dplyr::count(dplyr::across(dplyr::all_of(colunas))) %>%
        dplyr::filter(
            paciente_enumSexoBiologico %in% c("M", "F"),!is.na(paciente_idade),
            as.numeric(paciente_idade) >= 18,
            as.numeric(paciente_idade) <= 100
        ) %>%
        dplyr::transmute(
            idade = as.numeric(paciente_idade),
            sexo = dplyr::if_else(paciente_enumSexoBiologico == "M", "Homem", "Mulher"),
            dose = stringr::str_squish(vacina_descricao_dose),
            n
        )
}

# transform ---------------------------------------------------------------

da_sumario <- purrr::map_dfr(skips, sumarizar, f, chunk_size, colunas, colunas_spec)
datasus_idade_sexo_dose <- da_sumario %>%
    dplyr::group_by(idade, sexo, dose) %>%
    dplyr::summarise(n = sum(n), .groups = "drop")

usethis::use_data(datasus_idade_sexo_dose, overwrite = TRUE)
```

### PNAD 
```{r}
library(PNADcIBGE)

dadosPNADc <- get_pnadc(year = 2020, quarter = 4, vars=c("V2007", "V2009"))
totalsexo <- survey::svytotal(~interaction(V2007, V2009), dadosPNADc, na.rm = TRUE)

pop_idade_sexo <- tibble::tibble(
    nm = names(totalsexo),
    pop = as.numeric(totalsexo)
) %>%
    dplyr::transmute(
        sexo = stringr::str_extract(nm, "[HM][a-z]+"),
        idade = stringr::str_extract(nm, "(?<=\\.)[0-9]+$"),
        pop
    )

usethis::use_data(pop_idade_sexo, overwrite = TRUE)
```

## Population 
```{r}
library(ggplot2)
library(vacinaBrasil)

fonte <- stringr::str_glue(
    "Fonte:\n",
    "População: PNAD Contínua\n",
    "Vacinação: Open DataSus"
)

dose <- datasus_idade_sexo_dose %>% 
    dplyr::select(sexo, idade, tipo = dose, n) %>% 
    dplyr::filter(tipo %in% c("1ª Dose", "2ª Dose"))

pop <- pop_idade_sexo %>% 
    dplyr::transmute(
        sexo,
        idade = as.numeric(idade),
        tipo = "População",
        n = pop 
    ) %>% 
    dplyr::filter(idade <= 100, idade >= 18)

dados <- dplyr::bind_rows(pop, dose)

dados %>% 
    dplyr::mutate(n = n * ((sexo == "Homem") * 2 -1)) %>% 
    dplyr::mutate(tipo = forcats::lvls_reorder(tipo, c(2, 1, 3))) %>% 
    ggplot(aes(x = n, y = factor(idade), fill = sexo, alpha = tipo)) +
    geom_col(width = 1, position = "identity") +
    annotate(geom = "text", x = 0, y = seq(3, 73, 10), label = seq(20, 90, 10)) +
    scale_x_continuous(
        breaks = seq(-1500, 1500, 500) * 1000,
        labels = paste0(abs(seq(-1500, 1500, 500)), "K")
    ) +
    scale_y_discrete(breaks = seq(0, 100, 10)) + 
    scale_fill_viridis_d(begin = .3, end = .8, option = "C") +
    scale_alpha_manual(values = c(1, .6, .3)) +
    theme_minimal() +
    labs(
        x = "População", 
        y = "Idade",
        fill = "",
        alpha = "",
        title = "Vacinação no Brasil",
        caption = fonte
    ) +
    guides(fill = guide_legend(reverse = TRUE)) +
    theme(
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "top",
        plot.title = element_text(hjust = .5)
    )
```

## Proporcional
```{r}
# Proporcional
dados %>% 
    dplyr::mutate(n = n * ((sexo == "Homem") * 2 -1)) %>% 
    tidyr::pivot_wider(names_from = tipo, values_from = n) %>% 
    janitor::clean_names() %>% 
    dplyr::mutate(
        prop1 = x1a_dose / abs(populacao)
        prop2 = x2a_dose / abs(populacao)
    ) %>% 
    dplyr::select(sexo, idade, prop1, prop2) %>% 
    tidyr::pivot_longer(c(prop1, prop2), names_to = "tipo", values_to = "n") %>% 
    dplyr::mutate(n = pmin(abs(n), 1) * sign(n)) %>% 
    dplyr::mutate(tipo = dplyr::if_else(tipo == "prop1", "1ª Dose", "2ª Dose")) %>% 
    dplyr::mutate(tipo = forcats::lvls_reorder(tipo, c(2, 1))) %>% 
    ggplot(aes(x = n, y = factor(idade), fill = sexo, alpha = tipo)) +
    geom_col(width = 1, position = "identity") +
    annotate(geom = "text", x = 0, y = seq(3, 73, 10), label = seq(20, 90, 10)) +
    scale_x_continuous(
        breaks = seq(-1, 1, .2),
        labels = scales::percent(abs(seq(-1, 1, .2)))
    ) +
    scale_y_discrete(breaks = seq(0, 100, 10)) + 
    scale_fill_viridis_d(begin = .3, end = .8, option = "C") +
    scale_alpha_manual(values = c(1, .6, .3)) +
    theme_minimal() +
    labs(
        x = "Proporção da população", 
        y = "Idade",
        fill = "",
        alpha = "",
        title = "Vacinação no Brasil",
        caption = fonte
    ) +
    guides(fill = guide_legend(reverse = TRUE)) +
    theme(
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "top",
        plot.title = element_text(hjust = .5)
    )
```

## References
Refactor from open source code at [github](https://github.com/jtrecenti/vacinaBrasil).
Original [idea of Elias Krainski](https://twitter.com/eliaskrainski/status/1385056297322696709/photo/1) from UFPR.